### ISSUE TITLE
Crash on 1.62

### ISSUE THREAD

**Issue by MCChristor** [psiberx/cp2077-archive-xl#2]
Does crash at startup:

Registered crash info file...
InternalVersion: 3.0.4666417  P4CL: 6067695  Stream: R6.Release 
!!!CRASHED!!!
Error Reason: Assert
Expression: result
Message: Failed to initialize scripts data!
File: E:\R6.Release\dev\src\common\engine\src\baseEngineInit.cpp
Line: 1022

"uptimeSeconds":4
"stopThreadID":272
"exceptionCode":0x80000003
"processID":268
"Engine/CommitFailedErrorCode@1#TID=0":"0"
"Configuration/Name@2#TID=0":"FINAL"
"Configuration/Name2@3#TID=0":"FINAL"
"Game/Patch@7#TID=0":"1.62"
"Engine/OOM@4#TID=0":"false"
"GlobalMode/IsClosing@5#TID=0":"false"
"GlobalMode/IsGame@86#TID=0":"true"
"Jobs/InitParam/MaxLatentJobs@8#TID=0":"131072"
"Jobs/InitParam/MaxCriticalPathJobs@9#TID=0":"65536"
"Jobs/InitParam/MaxImmediateJobs@10#TID=0":"2048"
"Jobs/InitParam/WorkerThreadStackSizeKB@11#TID=0":"1024"
"Jobs/InitParam/MaxThreads@12#TID=0":"27"
"Jobs/InitParam/AllJobsCriticalPath@14#TID=0":"false"
"Jobs/InitParam/UseJobDebugger@13#TID=0":"false"
"Jobs/Dispatcher/NumDispatcherThreads@15#TID=0":"11"
"Jobs/Dispatcher/MaxHWConcurrency@16#TID=0":"12"
"Engine/InitParams/InteropStartingPort@87#TID=0":"0"
"Engine/InitParams/RenderPreset@88#TID=0":"1"
"Engine/InitParams/QualityLevelName@89#TID=0":"None"
"Engine/InitParams/TextureQualityLevelName@90#TID=0":"High"
"Engine/InitParams/WatchdogTimeoutSecondsOverride@91#TID=0":"0"
"Engine/InitParams/ScriptsSilentCompilation@92#TID=0":"false"
"Engine/InitParams/ScriptsSilentValidation@93#TID=0":"false"
"Engine/InitParams/TweakDBSilentValidation@94#TID=0":"false"
"Engine/InitParams/PvdDumpToFile@95#TID=0":"false"
"Engine/InitParams/ProfilerEnabled@96#TID=0":"false"
"Engine/InitParams/ShowVersionWatermark@97#TID=0":"true"
"Engine/InitParams/WindowCaption@98#TID=0":""
"Engine/PC/SystemName@99#TID=0":"Windows 10 Pro"
"Engine/PC/SystemVersion@100#TID=0":"10.0.18363"
"Engine/SafeInit@107#TID=0":"DebugFilters"
"Engine/IsHeadless@102#TID=0":"false"
"Engine/VersionWatermark@101#TID=0":"3.0.4666417  P4CL: 6067695  Stream: R6.Release  Apr 18 2023 16:24:05  (FINAL) Total memory: 9863962624 bytes "
"Engine/Scripts/PrimaryBlobModifiedDate@110#TID=0":"133313446368729823"
"Engine/Scripts/FallbackBlobModifiedDate@111#TID=0":"0"
"Engine/Scripts/BlobPathUsed@116#TID=0":"None"
"Engine/Scripts/ShouldCompileScripts@108#TID=0":"true"
"Engine/Scripts/CompileScriptsSuccess@109#TID=0":"true"
"Engine/Scripts/Loaded@117#TID=0":"false"
"##CrashDump##/DumpCrashDataSeconds":"0"

**Comment by psiberx** [comment]
This is a common user side error unrelated to ArchiveXL. Follow general instructions for troubleshooting mods or visit community Discord for help.

**Comment by MCChristor** [comment]
Thx m8! Will look into it
