### ISSUE TITLE
Traffic XL - Feature Request

### ISSUE THREAD

**Issue by jamiecross1477** [psiberx/cp2077-archive-xl#3]
Is there a way for car mod creators to add an xl file to integrate their cars/ appearances into the traffic of NC? If not, could there be?

**Comment by psiberx** [comment]
It's not supported right now. If you can provide technical details on what exactly needs to be merged, extended, etc. I'll be able to start working on this feature sooner.

**Comment by jamiecross1477** [comment]
Doc Presto said it was community, scene and questphase. that's all I know about it- he probably knows way more

**Comment by psiberx** [comment]
You should figure out how to add traffic with existing tools first, then we can discuss how it can be improved by ArchiveXL.
