### ISSUE TITLE
visualTags for footstep sounds don't work on first load

### ISSUE THREAD

**Issue by Viscerous** [psiberx/cp2077-archive-xl#4]
When loading into the game for the first time, a player character already wearing modded footwear that's properly tagged with `visualTags` such as `Boots` or `Stilettos` will still sound barefoot until you change outfit or shoes. Alternatively, simply loading a save again also resolves the issue (it can be the exact same save loaded earlier).

Sadly this one is hard to reproduce because most mods do not come with tags for footwear at all. Equipment-EX can also be ruled out as it happens even when equipped in a regular slot without using its wardrobe system. Vanilla footwear doesn't seem to be affected, so I figured the issue would be either with ArchiveXL (or perhaps TweakXL?)

**Comment by psiberx** [comment]
Thank you for the info. I'll try to reproduce it.

**Comment by Etern213** [comment]
> Thank you for the info. I'll try to reproduce it.

Any clues? I'm having the same problem.

**Comment by psiberx** [comment]
Fixed in 1.14.4.
