### ISSUE TITLE
Feature request: partsValues for npc appearances

### ISSUE THREAD

**Issue by manavortex** [psiberx/cp2077-archive-xl#5]
It would be seriously cool if NPC appearances could support `partsValues`. I'd love to encapsulate e.g. hairstyles in a mesh entity, since it would make swapping out entire chunks for NPCs so much easier:

![image](https://github.com/user-attachments/assets/d6eaf419-b659-4bab-92b0-54a9b3489071)

**Comment by psiberx** [comment]
Done :)
